Joystick: Disable ubuntu x86_64 due to SDL issue
On Ubuntu x86_64, if joystick support is enabled then the build fails on
an obscure SIMDE failure with conflicting defines. It is not an issue on
aarch64. For the time being disable joystick in x86_64 until the issue
can be investigated.

For reference, here is the seen failure:

```
FAILED: CMakeFiles/obs-ptz.dir/obs-ptz_autogen/mocs_compilation.cpp.o
[...]
  In file included from /usr/include/obs/util/simde/x86/sse2.h:35,
                   from /usr/include/obs/util/sse-intrin.h:30,
                   from /usr/include/obs/graphics/vec4.h:23,
                   from /usr/include/obs/graphics/vec3.h:21,
                   from /usr/include/obs/obs.h:26,
                   from /home/runner/work/obs-ptz/obs-ptz/build_x86_64/obs-ptz_autogen/KXJ5XCMQDR/../../../shared/properties-view/properties-view.moc.hpp:9,
                   from /home/runner/work/obs-ptz/obs-ptz/build_x86_64/obs-ptz_autogen/KXJ5XCMQDR/moc_properties-view.moc.cpp:10,
                   from /home/runner/work/obs-ptz/obs-ptz/build_x86_64/obs-ptz_autogen/mocs_compilation.cpp:2:
  /usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: ‘__m128 simde_x_mm_round_ps’ redeclared as different kind of entity
    125 | _mm_round_ps (__m128 __V, const int __M)
        | ^~~~~~~~~~~~
  /usr/include/obs/util/simde/x86/sse.h:410:13: note: previous declaration ‘simde__m128 simde_x_mm_round_ps(simde__m128, int, int)’
    410 | simde__m128 simde_x_mm_round_ps(simde__m128 a, int rounding, int lax_rounding)
        |             ^~~~~~~~~~~~~~~~~~~
  /usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: expected primary-expression before ‘__V’
    125 | _mm_round_ps (__m128 __V, const int __M)
        | ^~~~~~~~~~~~
  /usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: error: expected ‘)’ before ‘__V’
  /usr/lib/gcc/x86_64-linux-gnu/13/include/smmintrin.h:125:1: note: to match this ‘(’
    125 | _mm_round_ps (__m128 __V, const int __M)
        | ^~~~~~~~~~~~
```

Signed-off-by: Grant Likely <grant.likely@secretlab.ca>